const fs = require('fs');
const path = require('path');
const readline = require('readline');
const fse = require('fs-extra');

const ROOT = path.join(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');
const SETTINGS_FILE = path.join(ROOT, 'memory', 'settings.json');

function askFactory() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  const ask = (q) => new Promise((resolve) => rl.question(q, resolve));
  ask.close = () => rl.close();
  return ask;
}

function clean(v) {
  return String(v || '').trim();
}

function isYes(v) {
  return ['y', 'yes', 'да', 'д', 'true', '1'].includes(clean(v).toLowerCase());
}

function parseTimeToCron(value) {
  const v = clean(value || '22:30');
  const m = v.match(/^(\d{1,2}):(\d{2})$/);
  if (!m) throw new Error('Daily review time must be HH:MM, e.g. 22:30');
  const hour = Number(m[1]);
  const minute = Number(m[2]);
  if (hour < 0 || hour > 23 || minute < 0 || minute > 59) {
    throw new Error('Daily review time must be a valid 24-hour HH:MM value.');
  }
  return `${minute} ${hour} * * *`;
}

function validateTz(tz) {
  if (!tz) return '';
  new Intl.DateTimeFormat('en-US', { timeZone: tz }).format(new Date());
  return tz;
}

function envLine(key, value) {
  return `${key}=${String(value || '').replace(/\r?\n/g, '')}`;
}

async function main() {
  console.log('Galaxy S8 Agent setup');
  console.log('Secrets are saved to .env. Behavior settings go to memory/settings.json.');
  console.log('');

  if (fs.existsSync(ENV_FILE)) {
    const ask = askFactory();
    const overwrite = await ask('.env already exists. Overwrite it? [y/N] ');
    ask.close();
    if (!isYes(overwrite)) {
      console.log('Setup cancelled. Existing .env was not changed.');
      return;
    }
  }

  const ask = askFactory();
  try {
    const telegramToken = clean(await ask('Telegram bot token: '));
    const openrouterKey = clean(await ask('OpenRouter API key: '));
    const userIds = clean(await ask('Your Telegram user id (comma-separated if multiple): '));
    const groqKey = clean(await ask('Groq API key for voice-to-text (optional, Enter to skip): '));
    const tz = validateTz(clean(await ask('Timezone [Europe/Moscow]: ')) || 'Europe/Moscow');
    const reviewTime = clean(await ask('Daily review time [22:30]: ')) || '22:30';

    if (!telegramToken) throw new Error('Telegram bot token is required.');
    if (!openrouterKey) throw new Error('OpenRouter API key is required.');
    if (!userIds) throw new Error('Telegram user id is required.');

    const env = [
      '# Galaxy S8 Agent secrets/bootstrap',
      '# Generated by npm run setup',
      envLine('TELEGRAM_BOT_TOKEN', telegramToken),
      envLine('ALLOWED_TELEGRAM_USER_IDS', userIds),
      envLine('OPENROUTER_API_KEY', openrouterKey),
      envLine('OPENROUTER_MODEL', 'deepseek/deepseek-chat'),
      envLine('GROQ_API_KEY', groqKey),
      envLine('GROQ_STT_MODEL', 'whisper-large-v3-turbo'),
      envLine('ALLOW_SHELL', 'false'),
      '',
    ].join('\n');

    await fse.writeFile(ENV_FILE, env, { mode: 0o600 });

    await fse.ensureDir(path.dirname(SETTINGS_FILE));
    const settings = {
      stt: {
        enabled: !!groqKey,
        language: 'ru',
        maxDurationSec: 300,
      },
      dailyReview: {
        enabled: true,
        cron: parseTimeToCron(reviewTime),
        tz,
        minMessages: 3,
        prevDays: 3,
        model: '',
      },
      silent: {
        reaction: '✍',
        autoExitOnDailyReview: true,
      },
      chats: {},
    };
    await fse.writeJson(SETTINGS_FILE, settings, { spaces: 2 });

    console.log('');
    console.log('Setup complete.');
    console.log('Run: npm run doctor');
    console.log('Start: agent-start  (or npm start)');
  } finally {
    ask.close();
  }
}

main().catch((err) => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
